# .github/workflows/setup-runner.yml

name: Setup GitHub Runner with Ansible

on:
  workflow_dispatch:

jobs:
  setup-runner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Runner requirement
        run: |
          usermod -a -G sudo "$(id -un)"
          echo "%sudo ALL = (ALL) NOPASSWD: ALL" | sudo tee -a /etc/sudoers
          curl https://get.docker.com | sh
          sudo chmod o+rw /var/run/docker.sock

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Check whoami
        run: |
          whoami

      - name: Run Ansible Playbook to Install Tools
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'False'
        run: |
          ansible-playbook -i "localhost," -c local ansible/playbook.yml
