name: CICD for Monitoring application
on:
  workflow_dispatch:
    inputs:
      region:
        description: 'Region to deploy'
        required: true
        default: 'JP'
        type: choice
        options:
          - JP
          - NAM
          - EU
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
env:
  AZURE_WEBAPP_NAME: your-app-name    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '20.x'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code checkout
      uses: actions/checkout@v4

    - name: Print details
      run: |
        chmod +x hey.sh
        bash ${GITHUB_WORKSPACE}/hey.sh ${{ inputs.region }} ${{ inputs.environment }}
     
